version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql_sample
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: sample
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - ./init.db:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"